# Generated by Django 4.2.2 on 2023-07-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_reviveuser_is_admin_alter_reviveuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('donation_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recived_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='files/')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reviveuser')),
            ],
        ),
    ]
