# Generated by Django 4.2.3 on 2023-07-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_gallerymanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanage',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventmanage',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
