# Generated by Django 4.2.3 on 2023-08-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisismanage',
            name='recived_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
