# Generated by Django 4.2.2 on 2023-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reviveuser_username_alter_reviveuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reviveuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviveuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
