# Generated by Django 4.2.2 on 2023-06-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reviveuser_email_alter_reviveuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
