# Generated by Django 4.2.2 on 2023-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reviveuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviveuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
