# Generated by Django 4.2.2 on 2023-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reviveuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='reviveuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
