# Generated by Django 4.2.2 on 2023-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reviveuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
