# Generated by Django 4.2.2 on 2023-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_reviveuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviveuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
