# Generated by Django 4.2.2 on 2023-06-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_reviveuser_is_active_alter_reviveuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviveuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
