# Generated by Django 4.2.2 on 2023-07-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reviveuser_is_admin_alter_reviveuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviveuser',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
